name: Auto Commit Daily

on:
  schedule:
    # 17:00 UTC = 00:00 (12h đêm) giờ Việt Nam
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_COMMIT_TOKEN }}

      - name: Update log file
        run: |
          echo "Last updated on $(date)" > auto_commit_log.txt

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update: $(date)"
          file_pattern: 'auto_commit_log.txt'
          commit_author: 'lptoan109 <lephuoctoan6411@gmail.com>'